config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>Copyright Chris Melanson this is subject to change didn't follow class instructions</p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">The Featherie</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Us", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<div class="blog-header">
  <div class="container">
    <p class="lead blog-description">Chris Melanson productions for pagination 22 minute lesson in styles.</p>
  </div>
</div>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template.</p>
    <%= link_to 'Write a new blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<h3 class="masthead-brand">The Featherie</h3>
<nav class="nav nav-masthead justify-content-center">
  <%= link_to "Home", root_path, class: 'nav-link' %>
  <%= link_to "About Me", about_me_path, class: 'nav-link' %>
  <%= link_to "Contact", contact_path, class: 'nav-link' %>
  <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
  <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
  <%= login_helper 'nav-link' %>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p>This is my blog it is all about golf and stuff.</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#">GitHub</a></li>
      <li><a href="#">Twitter</a></li>
      <li><a href="#">Facebook</a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">The Featherie</h3>
    <nav class="nav nav-masthead justify-content-center">
    <%= link_to "Home", root_path, class: 'nav-link' %>
    <%= link_to "About Us", about_me_path, class: 'nav-link' %>
    <%= link_to "Contact", contact_path, class: 'nav-link' %>
    <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
    <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a> |
    </p>
    <p>Featherie is a golf blog for all to enjoy! </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to "Find out more about us", about_me_path, class: 'btn btn-primary' %>
      <a href="#" class="btn btn-secondary my-2">Secondary action</a>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add information here.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><%= link_to "Home", root_path, class: 'nav-link' %></li>
            <li><%= link_to "About Me", about_me_path, class: 'nav-link' %></li>
            <li><%= link_to "Contact", contact_path, class: 'nav-link' %></li>
            <li><%= link_to "Blogs", blogs_path, class: 'nav-link' %></li>
            <li><%= link_to "Portfolio", portfolios_path, class: 'nav-link' %></li>
            <li><%= login_helper 'nav-link' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>The Featherie</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>